---
# Apply latest style guide and new cops
AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - spec/**/*
    - spec/*.rb
    - Gemfile
    - Rakefile
    - workers/*.rb
    - lib/*.rb
    
# ignore block length in test code only
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*
    - spec/*.rb
    - Gemfile
    - Rakefile